# Generated by Django 5.0.6 on 2024-06-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'cart item', 'verbose_name_plural': 'cart items'},
        ),
    ]
